// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUeepjyGOqsEHrWNCBRqUyuYmohGHz2Q',
    appId: '1:1025895290579:web:ca57e4385a301288f6a626',
    messagingSenderId: '1025895290579',
    projectId: 'letzeat-719fc',
    authDomain: 'letzeat-719fc.firebaseapp.com',
    storageBucket: 'letzeat-719fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSO8QAQI-cE3NvYweFWnYdkUPFRFe5z_M',
    appId: '1:1025895290579:android:3c81fd0742234c2df6a626',
    messagingSenderId: '1025895290579',
    projectId: 'letzeat-719fc',
    storageBucket: 'letzeat-719fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUP5TBQLlG432sm6ecVC2dc5rRtx7G24',
    appId: '1:1025895290579:ios:ff84d4f92c7b1b9df6a626',
    messagingSenderId: '1025895290579',
    projectId: 'letzeat-719fc',
    storageBucket: 'letzeat-719fc.firebasestorage.app',
    iosBundleId: 'com.example.letzeat',
  );
}
